fix(automap): fix naming conflicts for PostgreSQLProvider
geopython/pygeoapi pull request #1184
Opened 2023-03-22 11:47 UTC by MTachon

# Overview
Automapping classes and relationships from database schema throws an error if a column name is the same as a relationship name (see https://docs-sqlalchemy.readthedocs.io/ko/latest/orm/extensions/automap.html#handling-simple-naming-conflicts). This PR solves potential naming conflict problems by changing the relationship name if the original one is the same as existing column name.

# Related Issue / Discussion
Have not seen any related issue/discussion.

# Additional Information
No additional information.

# Contributions and Licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [x] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

2023-03-30 22:08 UTC, francbartoli requested changes
Is it possible to add a failing test for a conflict?

2023-03-31 07:16 UTC, MTachon commented
I guess a `get_collection_items` call on a minimal dataset with a *conflicting* table structure would do just fine. Will look into it!

2023-03-31 10:58 UTC, MTachon commented
I have extended the new test data file from PR https://github.com/geopython/pygeoapi/pull/1185 with two new (empty) tables, which results in pygeoapi throwing a `sqlalchemy.exc.ArgumentError` when attempting to publish the table `naming_conflicts_table`. A simple test was added to `test_postgresql_provider.py` which fails in master and passes in this branch.

2023-03-31 11:04 UTC, francbartoli approved these changes

2023-03-31 11:05 UTC, merged