Feature/mongodb jobmanager
geopython/pygeoapi pull request #1186
Opened 2023-03-23 09:47 UTC by xcomagent95

# Overview
A jobmanager for the pygeoapi employing the mongoDB. 

# Related Issue / Discussion

#1179 

# Additional Information

# Contributions and Licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [ ] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

2023-03-24 09:39 UTC, tomkralidis requested changes
Small changes suggested.

As well, add a section before https://github.com/geopython/pygeoapi/blob/master/docs/source/data-publishing/ogcapi-processes.rst#putting-it-all-together, called 'MongoDB', which provides 1-2 sentences on your plugin, as well as a sample configuration/example.

2023-03-27 16:23 UTC, tomkralidis requested changes
Thanks for the updates!  There are some flake8 errors that should be fixed (please ensure `flake8 pygeoapi/process/manager/mongodb_.py` runs without error).

As well, add a section before https://github.com/geopython/pygeoapi/blob/master/docs/source/data-publishing/ogcapi-processes.rst#putting-it-all-together, called 'MongoDB', which provides 1-2 sentences on your plugin, as well as a sample configuration/example.

2023-03-30 11:02 UTC, xcomagent95 commented
Hi,
I hope i could fix alle the issues mentioned.

2023-03-30 11:07 UTC, tomkralidis requested changes

2023-03-30 11:07 UTC, tomkralidis commented on pygeoapi-config.yml
> -
Add this blank line back.

2023-03-30 11:08 UTC, tomkralidis commented
FYI minor change request, and needs flake8 fixes. There are some flake8 errors that should be fixed (please ensure `flake8 pygeoapi/process/manager/mongodb_.py` runs without error).

2023-03-30 11:38 UTC, merged