Time Querying in EDR Provider
geopython/pygeoapi pull request #1247
Opened 2023-05-15 21:52 UTC by sjordan29

# Overview
Expanded capabilities for time queries in the EDR provider, including:

- Resolving `TypeError` for single time query with certain datetime formats
- Handling datetime queries with UTC timezone, specified with trailing `Z`
- Querying over bounded and unbounded time intervals

# Related Issue / Discussion
#1239 

# Contributions and Licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [x] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

2023-05-16 21:46 UTC, webb-ben approved these changes
+1

2023-05-16 21:46 UTC, webb-ben commented on pygeoapi/provider/xarray_edr.py
> +        :returns: xarray datetime query
Add empty line before first `:param:` and before `:return:` in function headers. i.e.
```
        Make xarray datetime query

        :param datetime_: temporal (datestamp or extent)

        :returns: xarray datetime query

2023-05-16 21:46 UTC, webb-ben commented on pygeoapi/provider/xarray_edr.py
> +            elif end == '..':
Although it would be redundant to do `?datetime=../..`, this would throw an error. Changing `elif end == '..':` to `if end == '..':` would prevent.

2023-05-17 01:09 UTC, tomkralidis requested changes
Minor change requests along with @webb-ben -- great work!

2023-05-17 01:09 UTC, tomkralidis commented on pygeoapi/provider/xarray_edr.py
> +import numpy as np
Add a blank line between modules from standard library and 3rd party, i.e.:

```python
import logging

import numpy as np

from pygeoapi.provider.base import ProviderNoDataError, ProviderQueryError
from pygeoapi.provider.base_edr import BaseEDRProvider
```

2023-05-18 01:19 UTC, merged

2023-05-18 01:19 UTC, tomkralidis commented
Thanks @sjordan29 !