Process manager instantiates processor
geopython/pygeoapi pull request #1278
Opened 2023-06-22 11:40 UTC by ricardogsilva

# Overview

**NOTE: This PR builds upon #1277 - Please review it first**

This PR implements the `get_processor()` method on the `BaseManager` class, thus making the manager responsible for instantiating a processor, as discussed in #1201. The base manager still calls `load_plugin` internally, but this is now an implementation detail, which means that custom managers could use an alternative method for loading processes, if needed. 

# Related Issue / Discussion
- Fixes #1201 

# Contributions and Licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [x] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

2023-07-01 20:44 UTC, ricardogsilva commented
@tomkralidis ready for review now

2023-07-01 21:07 UTC, francbartoli requested changes

2023-07-01 21:07 UTC, francbartoli commented on tests/test_manager.py
> +# Authors: Ricardo Garcia Silva <ricardo.garcia.silva@geobyond.it>
There is a typo in the email

2023-07-02 08:39 UTC, francbartoli approved these changes

2023-07-02 08:51 UTC, merged