Oracle Provider
geopython/pygeoapi pull request #1329
Opened 2023-08-03 12:47 UTC by totycro

# Overview
Oracle Provider for pygeoapi implemented by @xkosubek

The implementation is modeled after the PostgreSQL provider and thus should be fairly consistent with related code in pygeoapi. 

It supports all CRUD operations.

The tests are executed via GitHub Actions using an oracle docker container.

There is some documentation, specifically also for the `SqlManipulator`, which is a mechanism for custom extensions that is necessary for a certain private use case, but is designed to be useable for different contexts.

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [X] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [X] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

2023-08-18 20:43 UTC, tomkralidis requested changes
Excellent work here and super easy/pleasant to review.  See minor change requests.  Thanks!

2023-08-18 20:43 UTC, tomkralidis commented on docs/source/data-publishing/ogcapi-features.rst
> +The provider supports a SQL-Manipulator-Plugin class. With this, the SQL statement could be manipulated. This is
Perhaps this level of information (code blocks, etc.) can go in `pygeoapi/provider/oracle.py` and specify in the doc to consult the plugin itself?  We should keep these sections of the docs more user focused.

2023-08-18 20:43 UTC, tomkralidis commented on oracle-config.yml
Remove this file (given we have an example in `tests`.

2023-08-18 20:43 UTC, tomkralidis commented on oracle-openapi.yml
Remove this file.

2023-08-18 20:43 UTC, tomkralidis commented on pygeoapi/provider/oracle.py
> +
Sort dependencies as standard library, external packages, local imports, alphabetically.  So:

```python
import importlib
import json
import logging
from typing import Optional

import oracledb

from pygeoapi.provider.base import (
    BaseProvider,
    ProviderConnectionError,
    ProviderItemNotFoundError,
    ProviderQueryError
)
```

2023-08-18 20:43 UTC, tomkralidis commented on pygeoapi/provider/oracle.py
> +            sdo_mask = "mask={}".format(sdo_mask)
use f-string

2023-08-18 20:43 UTC, tomkralidis commented on pygeoapi/provider/oracle.py
> +            where_dict["clause"] = " WHERE {}".format(
use f-string

2023-08-18 20:43 UTC, tomkralidis commented on pygeoapi/provider/oracle.py
> +        "reading class {} from module {}".format(class_name, module_name)
use f-string

2023-08-18 20:43 UTC, tomkralidis commented on pygeoapi/provider/oracle.py
> +        ), "class {} should inherit from {}".format(
use f-string

2023-08-18 20:43 UTC, tomkralidis commented on pygeoapi/provider/oracle.py
> +    LOGGER.debug("initialising {} with params {}".format(class_name, kwargs))
use f-string

2023-08-25 15:15 UTC, xkosubek commented
Thanks for the laud! I'll try to fix everything in the next days.

2023-08-25 17:37 UTC, tomkralidis commented on docs/source/data-publishing/ogcapi-features.rst
> +The provider supports a SQL-Manipulator-Plugin class. With this, the SQL statement could be manipulated. This is
+1

2023-09-12 14:58 UTC, webb-ben commented on oracle-config.yml
If the full configuration files are beneficial to keep, alternatively consider creating an [oracle docker example](https://github.com/geopython/pygeoapi/tree/master/docker/examples).

2023-09-12 14:58 UTC, webb-ben commented on tests/pygeoapi-test-config-oracle.yml
@tomkralidis I believe this file can be deleted too - https://github.com/geopython/pygeoapi/pull/1329/files#diff-bec70aa2812a4deafc7d4f626335d69a1467963368c7b7946d62462d38abe7afR121

2023-09-27 06:54 UTC, xkosubek commented on oracle-config.yml
No, there is no benefit. Everything is in the documentation, too. I only forgot to delete this file...

2023-09-27 07:03 UTC, xkosubek commented on tests/pygeoapi-test-config-oracle.yml
Yes, the configuration is included in the test class.

2023-09-27 07:17 UTC, xkosubek commented
All change requests are now implemented and commited!

2023-09-27 11:07 UTC, merged