Support jsonld for items with null geometry
geopython/pygeoapi pull request #1423
Opened 2023-12-07 16:51 UTC by doublebyte1

# Overview

Some items, like records, may have no geometry . This is throwing an error on the jsonld representation, because it always expect a geometry. This fix will avoid geometry operations over items that have a null geometry.

# Related Issue / Discussion

https://github.com/geopython/pygeoapi/issues/1422

# Contributions and Licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [ ] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [ ] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

2023-12-08 10:49 UTC, doublebyte1 commented
> Think the `@id` needs to be outside of the if block
> 
> ```
>         # Include multiple geometry encodings
>         if data.get('geometry') is not None:
>             data['type'] = 'schema:Place'
>             jsonldify_geometry(data)
> 
>         # Set data id
>         data['@id'] = identifier
> ```

You are right: this was leaving the id out for geometry null items. Thanks for spotting that: fixed now!

2023-12-08 15:21 UTC, webb-ben approved these changes

2023-12-08 15:48 UTC, tomkralidis requested changes

2023-12-10 11:36 UTC, doublebyte1 commented on pygeoapi/linked_data.py
> +        # if data.get('geometry') is not null:
Sure! https://github.com/doublebyte1/pygeoapi/commit/01fa0e69c0358bcc40024ad20a91c6a4ab86ea9e

2023-12-10 12:00 UTC, merged