Logfile rotation and configurable log format
geopython/pygeoapi pull request #1438
Opened 2023-12-18 17:02 UTC by totycro

# Overview

This reopens a previous PR under a different user: #1411

* Added configurable log and date format
* Added support for logfile rotation
* Updated documentation

# Related Issue / Discussion

fixes https://github.com/geopython/pygeoapi/issues/1389
fixes https://github.com/geopython/pygeoapi/issues/1388

# Additional Information

# Contributions and Licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [X] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [X] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

2024-01-03 13:25 UTC, tomkralidis requested changes
Please also add the new options to the [config schema](https://github.com/geopython/pygeoapi/blob/master/pygeoapi/schemas/config/pygeoapi-config-0.x.yml)

2024-01-03 13:25 UTC, tomkralidis commented on pygeoapi/log.py
> +from logging.handlers import RotatingFileHandler
Move to above the `sys` import (alphabetical order).

2024-01-04 13:46 UTC, tomkralidis requested changes

2024-01-04 15:12 UTC, totycro commented
All comments here should now have been addressed

2024-01-04 15:30 UTC, merged