MVT Provider refactoring
geopython/pygeoapi pull request #1454
Opened 2023-12-22 13:30 UTC by doublebyte1

# Overview
This PR introduces a refactoring in the MVT provider class. The MVT Provider becomes a base class, which is implemented through different providers. The tippecanoe and elastic MVT providers are also offered in this PR.

Tests, documentation and docker examples are also updated accordingly.

# Related Issue / Discussion
https://github.com/geopython/pygeoapi/issues/1450

# Contributions and Licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [ ] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [ ] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

2023-12-22 16:33 UTC, tomkralidis reviewed
Minor change requests -- great work!

2023-12-22 16:33 UTC, tomkralidis commented on docker/examples/MVT-elastic/ES/Dockerfile
Rename to `docker/examples/mvt-elastic/ES/Dockerfile`

2023-12-22 16:33 UTC, tomkralidis commented on docker/examples/MVT-tippecanoe/README.md
Rename to `docker/examples/mvt-tippecanoe/README.md`

2023-12-22 16:33 UTC, tomkralidis commented on docs/source/data-publishing/ogcapi-tiles.rst
> +^^^^^^^^^^^^^^^
Align

2023-12-22 16:33 UTC, tomkralidis commented on docs/source/data-publishing/ogcapi-tiles.rst
> +This code block shows how to configure pygeoapi to read Mabox vector tiles generated with tippecanoe, from disk or a URL.
`s/Mabox/Mapbox/`

2023-12-22 16:33 UTC, tomkralidis commented on pygeoapi/plugin.py
> +        'MVT-tippecanoe':
Put these on single lines and `#noqa`

2023-12-23 13:32 UTC, tomkralidis requested changes

2023-12-23 13:32 UTC, tomkralidis commented on .gitignore
> +.pygeoapi/docker/examples/MVT-elastic/ES/data
`s/MVT-elastic/mvt-elastic/`

2023-12-23 22:22 UTC, tomkralidis approved these changes

2023-12-23 22:22 UTC, tomkralidis commented
Over to @francbartoli for review/approve.

2023-12-27 15:32 UTC, francbartoli requested changes

2023-12-27 15:32 UTC, francbartoli commented on pygeoapi/provider/mvt_elastic.py
> +        self.tile_type = 'vector'
This is redundant because already set in the super class

2023-12-28 21:23 UTC, francbartoli approved these changes
Great work here @doublebyte1

2023-12-28 21:23 UTC, merged

2023-12-29 11:21 UTC, justb4 commented
Shortly after this merge we got a [GeoHealthCheck failure report](https://demo.geohealthcheck.org/resource/575) for the demo server. Maybe good to always check after a merge here as the pygeoapi Docker image is deployed there at https://demo.pygeoapi.io/master via CI/CD-chain (may take some time though). But looks related, maybe a config thing, to this PR.

```
pygeoapi.plugin.InvalidPluginError: Plugin MVT not found
ERROR: openapi.yml could not be generated ERROR
```

2023-12-29 12:51 UTC, tomkralidis commented
Thanks @justb4; PR in https://github.com/geopython/demo.pygeoapi.io/pull/48

Note: also see PR in #1463 that adds a checkbox to PR templates.