Saya/oracle pagination
geopython/pygeoapi pull request #1669
Opened 2024-05-28 02:30 UTC by 8luewater

# Overview
We found a few opportunities to increase convenience with clients who use datasets from Oracle databases in pygeoapi. The changes in this PR are tested with large Oracle datasets that Geoscience Australia (https://www.ga.gov.au/) manages on behalf of public stakeholders.

# Related Issue / discussion

1. Oracle provider did not stand up: With the latest master, pygeoapi did not start correctly when Oracle layers were included in the config yml file. To fix this, we added oracledb in the requirements.txt and this resolved the issue.
2. Pagination did not show up on Oracle Items page: Items page for Oracle layers did not show up. numbersMatched value to be returned in query function. The changes in oracle.py fixed this issue.

# Additional information
I believe that the changes are very much relevant for anyone using Oracle layers in pygeoapi.

# Appreciation
Thank you very much for your time and consideration about my pull request. Working with pygeoapi is one of my happiest times.

2024-05-28 03:01 UTC, tomkralidis requested changes

2024-05-28 03:03 UTC, tomkralidis commented
cc @totycro

2024-05-28 10:12 UTC, 8luewater commented on requirements.txt
> +oracledb==2.2.0
Thank you for your comment. I moved the line to requirements-provider.txt - Kind regards, Saya

2024-05-29 06:29 UTC, tomkralidis commented on requirements-provider.txt
> +oracledb==2.2.0
@8luewater Do we need to pin to 2.2.0 or can we default to latest (2.2.1)?  I would prefer having unpinned dependencies in master for providers to keep us current.

2024-05-29 06:30 UTC, tomkralidis requested changes
Requesting unpinning of oracledb pip requirement.

2024-05-29 12:03 UTC, 8luewater commented
Thank you for your another comment. Unpinned.

2024-05-29 23:47 UTC, tomkralidis commented
Thanks @8luewater. I updated the Pull Request text to the default template, which includes a couple of checkboxes.  Your PR can be checked off for Dependencies and public demo updates (since neither are affected).  You also need to checkoff the contributor checkboxes before we can merge.  Thanks.

2024-05-30 18:50 UTC, merged