Custom esri token service
geopython/pygeoapi pull request #1813
Opened 2024-09-19 13:09 UTC by colin-geo

# Overview
This PR updates the Esri provider so that a custom token generation service url can be passed through configuration to enable fetching of data from a self-hosted ArcGIS Server instance.

# Related Issue / discussion
Fixes geopython/pygeoapi#1812

# Additional information
None 

# Dependency policy (RFC2)

- [X] I have ensured that this PR meets [RFC2](https://pygeoapi.io/development/rfc/2) requirements

# Updates to public demo

- [X] I have ensured that breaking changes to the [pygeoapi master demo server](https://github.com/geopython/demo.pygeoapi.io) have been addressed
  - [X] https://github.com/geopython/demo.pygeoapi.io/blob/master/services/pygeoapi_master/local.config.yml

# Contributions and licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [X] I'd like to contribute bugfix to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution
- [X] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

2024-09-26 13:26 UTC, webb-ben requested changes
Looks good. Small changes. Can we also add the new fields to the ESRI OAF Provider documentation (https://github.com/geopython/pygeoapi/blob/master/docs/source/data-publishing/ogcapi-features.rst#esri-feature-service)

2024-09-26 13:26 UTC, webb-ben commented on pygeoapi/provider/esri.py
> +        self.token_referer = provider_def.get('referer')
```suggestion
        self.token_url = provider_def.get('token_service', ARCGIS_URL)
        self.token_referer = provider_def.get('referer', GENERATE_TOKEN_URL)
```

2024-09-26 13:26 UTC, webb-ben commented on pygeoapi/provider/esri.py
> +
```suggestion

```

2024-09-26 13:26 UTC, webb-ben commented on pygeoapi/provider/esri.py
> +
```suggestion

```

2024-09-26 13:26 UTC, webb-ben commented on pygeoapi/provider/esri.py
> +                'referer': (ARCGIS_URL if self.token_referer is None else self.token_referer)
```suggestion
                'referer': self.token_referer
```

2024-09-26 13:26 UTC, webb-ben commented on pygeoapi/provider/esri.py
> +            with self.session.post((GENERATE_TOKEN_URL if self.token_url is None else self.token_url), data=params) as r:
```suggestion
            with self.session.post(self.token_url, data=params) as r:
```

2024-10-01 12:08 UTC, colin-geo commented
I have incorporated the suggestions.

2024-10-01 14:28 UTC, webb-ben approved these changes

2024-10-01 14:53 UTC, merged