Added example for the Open API definition of the PUT admin/config path
geopython/pygeoapi pull request #1848
Opened 2024-11-18 10:53 UTC by doublebyte1

# Overview

With this example, users are able to try the PUT request and change their admin config.

# Related Issue / discussion

https://github.com/geopython/pygeoapi/issues/1847

# Additional information

# Dependency policy (RFC2)

- [ ] I have ensured that this PR meets [RFC2](https://pygeoapi.io/development/rfc/2) requirements

# Updates to public demo

- [ ] I have ensured that breaking changes to the [pygeoapi master demo server](https://github.com/geopython/demo.pygeoapi.io) have been addressed
  - [ ] https://github.com/geopython/demo.pygeoapi.io/blob/master/services/pygeoapi_master/local.config.yml

# Contributions and licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [ ] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution
- [ ] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

2024-11-21 02:20 UTC, tomkralidis requested changes

2024-11-21 02:20 UTC, tomkralidis commented on pygeoapi/openapi.py
> +    if len(cfg['resources']) < 1 or cfg['resources']['obs'] is None:
Apply to other parts of PR as well:

```python
    if len(cfg['resources']) < 1 or cfg['resources'].get('obs') is None:
```

2024-11-21 09:20 UTC, doublebyte1 commented on pygeoapi/openapi.py
> +    if len(cfg['resources']) < 1 or cfg['resources']['obs'] is None:
Done! 👍🏽

2024-11-22 12:58 UTC, doublebyte1 commented
@tomkralidis I fixed the build errors

2024-12-06 21:33 UTC, webb-ben approved these changes

2024-12-14 14:36 UTC, closed without merging