add schema.org/Dataset representation for items of ogc api records
geopython/pygeoapi pull request #655
Opened 2021-03-03 23:15 UTC by pvgenuchten

This PR adds a representation of the record schema of OGC API Records as json-ld.
Most of the field mappings are managed from the ld-context (and could probably be managed from the existing context configuration. However the 'properties' object of geojson itself, and the associations/distributions require specific changes. The frequent use of 'type' as a property name is not optimal for a ld conversion.

currently this is a work in progress
- [ ] finalization of the record schema (how will associations be constructed)
- [ ] populating more properties in record.yml, such as thumbnail, license, encodingformat, creator (contactPoint)
- [ ] tests and flake8
- [x] tested in GGL structured data testing tool and is functional (for jsonld as well as html encoding)

2021-03-04 00:38 UTC, alpha-beta-soup commented on pygeoapi/linked_data.py
> +        crds = feature.get('geometry',{}).get('coordinates',[[]])[0]
You could replace `get` with `pop` and remove the `pop` on l280. Pop returns the value (or a default) value in the same way as get, but also removes it.

2021-04-28 00:35 UTC, tomkralidis requested changes

2021-04-28 00:35 UTC, tomkralidis commented on pygeoapi/api.py
> +            itemType = self.config['resources'][dataset].get('providers', [{}])[0].get('type','')
Can be written as:

```python
try:
    _ = get_provider_by_type(se.f.config['resources'][dataset]['providers'], 'record')
    content = geojson2recordjsonld(self.config, content, dataset)
except ProviderTypeError:
    content = geojson2geojsonld(self.config, content, dataset)

2021-04-28 00:35 UTC, tomkralidis commented on pygeoapi/api.py
> +            itemType = self.config['resources'][dataset].get('providers', [{}])[0].get('type','')
Same here as previous comment.

2021-04-28 00:35 UTC, tomkralidis commented on pygeoapi/linked_data.py
> +    if isCollection:
Prefer `snake_case` for variables.

2021-09-14 19:43 UTC, tomkralidis commented
@pvgenuchten any update on this PR or should we close for now?

2021-09-14 20:51 UTC, pvgenuchten commented
Ah, I was not aware this was still pending, let me have a look asap

2024-03-24 03:19 UTC, closed without merging