Add support for deploying pygeoapi as a lambda container
geopython/pygeoapi pull request #709
Opened 2021-06-09 19:07 UTC by christophersbarrett

The base pygeoapi implementation can deployed as a lambda function, but once you start adding geo processing libraries it quickly exceeds the 250MB limit that AWS puts on deployed lambda functions. To still use pygeoapi as a lambda, you need to deploy it as a lambda container.

2021-06-11 13:20 UTC, christophersbarrett commented
Unsure how to deal with that failing build ^^ The file it is complaining about is moved to the top level per the readme.

2021-06-17 23:45 UTC, tomkralidis requested changes
cc'ing @bitner @jvanulden and @bo-lu here for possible feedback as well.

2021-06-17 23:45 UTC, tomkralidis commented on aws-lambda/container/.serverless-wsgi
> +{"app":"pygeoapi/flask_app.APP","text_mime_types":["application/ld+json"]}
Do we need to add all the default supported text MIME types here?

- `application/json`
- `text/html`
- `application/geo+json`
- `application/prs.coverage+json`
- `application/xml`

2021-06-17 23:45 UTC, tomkralidis commented on aws-lambda/container/wsgi.py
> +import os
The CI tests run flake8 and this file throws flake8 error. Does the following work?
```python
import os

from pygeoapi.flask_app import APP

os.environ['PYGEOAPI_CONFIG'] = 'pygeoapi-test-config.yml'
os.environ['PYGEOAPI_OPENAPI'] = 'pygeoapi-test-openapi.yml'

if __name__ == "__main__":
    APP.run()
```

2021-09-19 23:10 UTC, merged