add debian requirements
geopython/pygeoapi pull request #806
Opened 2021-10-30 00:01 UTC by tomkralidis

Testing 0.11.0 against via UbuntuGIS experimental yields import errors:

```
[Fri Oct 29 20:47:10.317465 2021] [wsgi:error] [pid 13248:tid 140203063650048] [remote 10.10.11.42:45584] mod_wsgi (pid=13248): Target WSGI script '/opt/woudc-api/app/woudc-api.wsgi' cannot be loaded as Python module.
[Fri Oct 29 20:47:10.317631 2021] [wsgi:error] [pid 13248:tid 140203063650048] [remote 10.10.11.42:45584] mod_wsgi (pid=13248): Exception occurred processing WSGI script '/opt/woudc-api/app/woudc-api.wsgi'.
[Fri Oct 29 20:47:10.317969 2021] [wsgi:error] [pid 13248:tid 140203063650048] [remote 10.10.11.42:45584] Traceback (most recent call last):
[Fri Oct 29 20:47:10.318051 2021] [wsgi:error] [pid 13248:tid 140203063650048] [remote 10.10.11.42:45584]   File "/opt/woudc-api/app/woudc-api.wsgi", line 67, in <module>
[Fri Oct 29 20:47:10.318100 2021] [wsgi:error] [pid 13248:tid 140203063650048] [remote 10.10.11.42:45584]     from woudc_api.app import app as application
[Fri Oct 29 20:47:10.318543 2021] [wsgi:error] [pid 13248:tid 140203063650048] [remote 10.10.11.42:45584]   File "/usr/lib/python3.6/dist-packages/woudc_api/app.py", line 51, in <module>
[Fri Oct 29 20:47:10.318627 2021] [wsgi:error] [pid 13248:tid 140203063650048] [remote 10.10.11.42:45584]     from pygeoapi.flask_app import BLUEPRINT as pygeoapi_blueprint
[Fri Oct 29 20:47:10.319009 2021] [wsgi:error] [pid 13248:tid 140203063650048] [remote 10.10.11.42:45584]   File "/usr/lib/python3/dist-packages/pygeoapi/flask_app.py", line 39, in <module>
[Fri Oct 29 20:47:10.319136 2021] [wsgi:error] [pid 13248:tid 140203063650048] [remote 10.10.11.42:45584]     from pygeoapi.api import API
[Fri Oct 29 20:47:10.319336 2021] [wsgi:error] [pid 13248:tid 140203063650048] [remote 10.10.11.42:45584]   File "/usr/lib/python3/dist-packages/pygeoapi/api.py", line 69, in <module>
[Fri Oct 29 20:47:10.319542 2021] [wsgi:error] [pid 13248:tid 140203063650048] [remote 10.10.11.42:45584]     from pygeoapi.models.cql import CQLModel
[Fri Oct 29 20:47:10.319691 2021] [wsgi:error] [pid 13248:tid 140203063650048] [remote 10.10.11.42:45584]   File "/usr/lib/python3/dist-packages/pygeoapi/models/cql.py", line 39, in <module>
[Fri Oct 29 20:47:10.319883 2021] [wsgi:error] [pid 13248:tid 140203063650048] [remote 10.10.11.42:45584]     from pydantic import BaseModel, Field
[Fri Oct 29 20:47:10.320103 2021] [wsgi:error] [pid 13248:tid 140203063650048] [remote 10.10.11.42:45584] ModuleNotFoundError: No module named 'pydantic'
```

Note that we will likely need Python elasticsearch_dsl packaging to cover the enhancements made in #723 (cc @francbartoli)

2021-10-30 09:16 UTC, kalxas commented
pydantic is available in Ubuntu Focal:
https://packages.ubuntu.com/search?keywords=python3-pydantic&searchon=names

elasticsearch-dsl is not available in Ubuntu
https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=python3-elasticsearch-dsl&searchon=names

2021-10-30 09:17 UTC, kalxas requested changes
Lets keep only pydantic as a requirement for now

2021-10-31 17:46 UTC, tomkralidis commented
@kalxas done.

2021-10-31 17:49 UTC, kalxas approved these changes

2021-10-31 17:49 UTC, merged