Hardcoded version of ES python library
geopython/pygeoapi pull request #862
Opened 2022-03-04 11:07 UTC by doublebyte1

Specified version of the python client of ES, to avoid breaking changes from version [v8.0.0](https://github.com/elastic/elasticsearch-py/releases/tag/v8.0.0).

2022-03-05 18:48 UTC, tomkralidis commented
Thanks @doublebyte1 !  Should we pin the ES requirement (perhaps to `<8`) in the following additional areas?

- https://github.com/geopython/pygeoapi/blob/master/requirements-provider.txt#L1
- https://github.com/geopython/pygeoapi/blob/master/debian/control#L26
- https://github.com/geopython/pygeoapi/blob/master/requirements-provider.txt#L13 (cc @francbartoli)

2022-03-07 15:36 UTC, doublebyte1 commented
@tomkralidis Please check my latest commit : https://github.com/geopython/pygeoapi/pull/862/commits/d93672ca9b37d06becc32971657ced3f1415e5f5

2022-03-07 15:41 UTC, tomkralidis requested changes

2022-03-07 15:41 UTC, tomkralidis commented on debian/control
> +Suggests: python3-babel, python3-elasticsearch<8.0.0, python3-fiona, python3-geojson, python3-pydantic, python3-pygeometa, python3-pyproj, python3-rasterio
I think this should be `python3-elasticsearch (<8)` ?

2022-03-07 15:41 UTC, tomkralidis commented on requirements-provider.txt
> +elasticsearch<8.0.0
`elasticsearch<8`

2022-03-07 15:41 UTC, tomkralidis commented on requirements-provider.txt
> +elasticsearch-dsl<8.0.0
`elasticsearch<8`

2022-03-08 18:18 UTC, francbartoli approved these changes

2022-03-08 18:19 UTC, merged